### PR TITLE
Provisioning: Add Browser policy support

### LINKED ISSUE #1368: Chrome: Add enterprise policy for LocalNetworkAccessAllowedForUrls
Image

Image

Since Chrome 139 to suppress a pop-up to Chrom(ium) users:
https://chromeenterprise.google/policies/#LocalNetworkAccessAllowedForUrls

* Currently, this only applies to HTTP/HTTPS requests, WS/WSS requests haven't been added to the specification
* NOTE:  This supersedes #1236 

This makes most sense for `localhost`, since any other DNS names would imply that the browser's running elsewhere.

See also: https://github.com/WICG/local-network-access/issues/16

To test:

1. Visit chrome://settings/performance
2. Select "Enable (Blocking)"
   Image
3. Restart the browser
4. Visit https://demo.qz.io
5. Paste the following code into terminal:
   ```js
   fetch('http://localhost:8182/json')
    .then(response => response.json())
    .then(data => console.log(data))
    .catch(error => console.error('Error:', error));
   ```

# Policy Examples

#### Windows Registry

```reg
Software\Policies\Google\Chrome\LocalNetworkAccessAllowedForUrls\1 = http://www.example.com:8080
Software\Policies\Google\Chrome\LocalNetworkAccessAllowedForUrls\2 = [*.]example.edu
Software\Policies\Google\Chrome\LocalNetworkAccessAllowedForUrls\3 = *
```

#### macOS Plist

```xml
<array>
<string>http://www.example.com:8080</string>
<string>[*.]example.edu</string>
<string>*</string>
</array>
```

#### Linux JSON
```json
[
 "http://www.example.com:8080",
 "[*.]example.edu",
 "*"
]
```

### PR DESCRIPTION
**Pull request by tresf**
This is an overhaul in the way we modify apps on the PC, specifically simplify and scope each task into a manageable codebase.  Prior to this PR, Chrome and Firefox used monolithic classes to apply any browser policies needed for QZ Tray to function properly, but this is not scalable for things like provisioning.

When this PR is merged, we expect to see something like this in our `provision.json`:

```json
    {
      "description": "[POLICY] URL for LNA at 'install'",
      "type": "policy",
      "os": "*",
      "name": "LocalNetworkAccessAllowedForUrls",
      "format": "indexed",
      "value": "[*.]qz.io"
    },
```

Closes #1368, well, at least for what we CAN do there.  `LocalNetworkAccess` in general is a bit too rigid for this to work anywhere EXCEPT Company Branded builds, sadly due to lack of TLD wildcard support.  See https://github.com/WICG/local-network-access for more info about this uphill battle (feel free to search by my username).

**WARNING:** This is a WIP branch and is not yet in a mergeable state, but has been opened for easier collaboration between developers.

### CODE REVIEW

File: src/qz/installer/apps/locator/AppLocator.java [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+                }
+            }
+        }
+        return pidMap;
+    }
+
+    public HashSet<String> getPids(HashSet<AppInfo> appList) {
+        HashSet<String> processNames = appList.stream()
+                .map(appInfo -> appInfo.getExePath().getFileName().toString())
+                .collect(Collectors.toCollection(HashSet::new));
```
Comment (Vzor-) [inline src/qz/installer/apps/locator/AppLocator.java]: Personal preference, but i always found stream.map to be hard to read. perhaps it could just be
``` java
    HashSet<String> processNames = new HashSet<>();

    for (AppInfo appInfo : appList) {
        processNames.add(appInfo.getExePath().getFileName().toString());
    }
```

**Comment by tresf** [comment]
Early mockup of @RebeccaDeField's artwork for browser restart messaging... 

https://github.com/user-attachments/assets/bd1994e6-5e1e-4a59-8a6a-bc71fb8c5193

File: test/qz/installer/apps/policy/GenericPolicyInstallerTests.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+
+    static Object[][] genericTests = {
+            {"testBool", true, VALUE},                                      //boolean
+            {"testInt", 1234, VALUE},                                       //integer
+            {"testFloat", 123.4, VALUE},                                    //decimal
+            {"testString", "test", VALUE},                                  //string
+            {"testArray", new Object[] {"element 1", "element 2"}, ARRAY},  //2-item array
+            {"testArray", new Object[] {"element 1"}, ARRAY},               //1-item array
+            {"testMap", new HashMap<String, Object>(Map.of(                 //map from map
+                    "key 1", "value 1",
```
Comment (tresf) [inline test/qz/installer/apps/policy/GenericPolicyInstallerTests.java]: It's rare for keys to have spaces in the names, perhaps `key1` or `keyOne`.

File: test/qz/installer/apps/policy/PolicyInstallerTestDispatcher.java [hunk 3]
```diff
@@ -3,32 +3,31 @@
...
+import qz.installer.Installer;
+import qz.installer.apps.locator.AppAlias;
 import qz.utils.SystemUtilities;
 
 import java.util.*;
 
-import static qz.installer.Installer.PrivilegeLevel;
-import static qz.installer.Installer.PrivilegeLevel.SYSTEM;
-import static qz.installer.Installer.PrivilegeLevel.USER;
-import static qz.installer.apps.locator.AppAlias.Alias;
```
[the remark this answers is not in the document]
Comment (Vzor-) [reply test/qz/installer/apps/policy/PolicyInstallerTestDispatcher.java]: I get Alias and AppAlias confused a lot, so I like seeing AppAlias.Alias. it just preference i can add the static import back in if needed.
